Models/Category/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMS23_Carousel.Models
{
    public class CategoryModel
    {
        public CategoryModel()
                {
            Id = Guid.NewGuid();
            IsActive = true;
        }
        public string Name{get;set;}="null";
        public Guid Id{get;set;}
        public string Description{get;set;}="null";
        public bool IsActive{get;set;}
    }
}

Models/Category/ICategoryRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AMS23_Carousel.Models.Interfaces;


namespace AMS23_Carousel.Models.Category
{
    public interface ICategoryRepository : IRepositoryBase<CategoryModel, Guid>
    {
        
    }
}

Models/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMS23_Carousel.Models
{
    public class CategoryModel
    {
        public CategoryModel(string description)
        {
            Id = Guid.NewGuid();
            Description = description;
            IsActive = true;
        }
        public Guid Id{get;set;}
        public string Description{get;set;}
        public bool IsActive{get;set;}
    }
}

Models/ErrorViewModel.cs
namespace AMS23_Carousel.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Interfaces/IRepositoryBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMS23_Carousel.Models.Interfaces
{
    public interface IRepositoryBase<TEntity, Tkey> where TEntity : class 
    {
        void Add(TEntity entity);
        void Delete(TEntity entity);
        void Update(TEntity entity);
      /*  IEnumerable<TEntity> GetAll(); ele funciona em base de memoria (ele filtra na tela do cliente)
        IQueryable<TEntity> GetAll(); uma lista que trabalha na base de dados (antes de ir para a tela do cliente ele é filtrado no banco de dados)
        ICollection<TEntity> GetAll();  */
        Task<TEntity> GetById(Guid Id);
             Task<IEnumerable<TEntity>> GetAll();
        Task<bool> SaveChangesAsync();

    }

 
}

Models/LoginModel.cs
namespace AMS23_Carousel.Models
{
    public class LoginModel
    {
        public string Email{get;set;}
        public string Password{get;set;}
    }
}

Controllers/CategoryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AMS23_Carousel.Models;
using AMS23_Carousel.Data;
using AMS23_Carousel.Models.Category;


namespace AMS23_Carousel.Controllers;

public class CategoryController : Controller
{
    private readonly ILogger<CategoryController> _logger;
    public readonly ICategoryRepository _categoryRepository;

    public CategoryController(ILogger<CategoryController> logger, ICategoryRepository categoryRepository)
    {
        _logger = logger;
        _categoryRepository = categoryRepository;
    }
    public IActionResult AddCat(CategoryModel category)
    {
        _categoryRepository.Add(category);
        _categoryRepository.SaveChangesAsync();
        return RedirectToAction("Index",category);
    }
    public IActionResult Add()
    {
        return View();
    }

 
    public async Task<IActionResult> Index()
    {
        return View(await _categoryRepository.GetAll());
    }
   
    public async Task<IActionResult> Delete(Guid Id)
    {
        return View( await _categoryRepository.GetById(Id));
    }

        public IActionResult DeleteCat(CategoryModel category)
    {
        _categoryRepository.Delete(category);
        _categoryRepository.SaveChangesAsync();
       
        return RedirectToAction("Index",category);
    }

    public async Task<IActionResult> Edit(Guid Id)
    {
        return View(await _categoryRepository.GetById(Id));
    }

    public IActionResult EditCat(CategoryModel category)
    {
        _categoryRepository.Update(category);
        _categoryRepository.SaveChangesAsync();
        return RedirectToAction("Index",category);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AMS23_Carousel.Models;
using AMS23_Carousel.Data;

namespace AMS23_Carousel.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Product()
    {
        return View();
    }

    public IActionResult Login(LoginModel loginModel)
    {
        var request = loginModel;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OrderController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AMS23_Carousel.Models;
using AMS23_Carousel.Data;

namespace AMS23_Carousel.Controllers;

public class OrderController : Controller
{
    private readonly ILogger<OrderController> _logger;

    public OrderController(ILogger<OrderController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    public IActionResult OrderCad()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Category/Add.cshtml
@model AMS23_Carousel.Models.CategoryModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="text-center">
    <div id="BackColor">


    <partial name="_carousel"/>
    </div>
    @using (Html.BeginForm("AddCategory", "Category", FormMethod.Post))
    {
        <forms>
        Descrição:<input type="text" asp-for="Description"><br>
        Nome:<input type="text" asp-for="Name"><br>
        <input type="submit" value="Adicionar Categoria">
    </forms>


}
</body>
</html>

Views/Category/Delete.cshtml
@model AMS23_Carousel.Models.CategoryModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="text-center">
    <div id="BackColor">
    

    <partial name="_carousel"/>
  
        <h1>Realmente deseja apagar @Model.Name?</h1>
        <h2>Descrição: @Model.Description</h2>
        <h2>Ativo?: @if(@Model.IsActive)
        {
         <label>Sim</label>
        }else
        {
            <label>Não</label>
        }</h2>
        <h2>Id: @Model.Id</h2>
        <a class="btn btn-danger" asp-controller="Category" asp-action="Index">Não</a>
        <a class="btn btn-primary" asp-route-Id="@Model.Id" asp-route-Name="@Model.Name" asp-route-Description="@Model.Description" asp-route-IsActive="@Model.IsActive" asp-controller="Category" asp-action="DeleteCat">Sim</a>
  </div>
</body>
</html>

Views/Category/Edit.cshtml
@model AMS23_Carousel.Models.CategoryModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="text-center">
    <div id="BackColor">
    

    <partial name="_carousel"/>
    </div>
    @using (Html.BeginForm("EditCat", "Category", FormMethod.Post))
    {
    <forms>
        <input type="hidden" asp-for="Id">
       Descrição:<input asp-for="Description" asp-type="text"><br>
        Name:<input asp-for="Name" asp-type="text"><br>
       <h4> Ativo?:<input type="checkbox" asp-for="IsActive"><br></h4>
        <input type="submit"  value="Adicionar Categoria">
    </forms>

}
</body>
</html>

Views/Category/Index.cshtml
@model IEnumerable<CategoryModel>
<div class="text-center">
    <h1>@ViewData["Title"]</h1>
    <div class="d-grid grid-gap-2">
        <a class="btn btn-primary" asp-controller="Category" asp-action="Add">Adicionar Categoria</a>
    </div>
    <br>
    <div id="BackColor">
    <forms>
<table class="table table-bordered border-dark">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Ativo?</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
    @if(Model != null && Model.Any())
    {
        foreach(var category in Model){
    <tr>
      <td scope="row">@category.Id</td>
      <td>@category.Name</td>
      <td>@category.Description</td>
       <td>@category.IsActive</td>
      <td><a class="btn btn-primary btn-sm" asp-route-Id="@category.Id" asp-controller="Category" asp-action="Edit">Editar</a>
          <a class="btn btn-danger btn-sm" asp-route-Id="@category.Id" asp-controller="Category" asp-action="Delete">Excluir</a>
      </td>
    </tr>
    }
}
  </tbody>
</table>
    </forms>
</div>
<partial name="_carousel"/>
</div>

Views/Home/Index.cshtml
<partial name="_carousel"/>

Views/Home/Login.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="~/css/custom.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input asp-type="text" asp-action="Login" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input asp-type="password" asp-action="Login" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<button asp-type="submit" asp-action="Login"  class="btn float-right login_btn">Jogar</button>
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

Views/Home/Product.cshtml
<div class="text-center">
<h1>@ViewData["Title"]</h1>
<div id=BackColor>
<forms>
    ID:<input type="Number" id="Id"><br>
    Description:<input type="text" id="Description"><br>
    ImageURL:<input type="url" name="" id="ImageURL"><br>
    Price:<input type="text" id="Price"><br>
    <input type="button" value="Done">


</forms>
</div>
<partial name="_carousel"/>
</div>

Views/Order/Index.cshtml
<div class="text-center">
<h1>@ViewData["Title"]</h1>
    <div class="d-grid gap-1">
    <a asp-controller="Order" asp-action="OrderCad" class="btn btn-primary btn-lg">Cadastrar Pedido</a>
</div>
<br>
    <table class="table table-bordered border-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Cliente</th>
      <th scope="col">Contato</th>
      <th scope="col">Hora do Pedido</th>
      <th scope="col">Estado</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>+55(16) 9934-4923</td>
      <td>18:42</td>
      <td>Entregue</td>
      <td><a class="btn btn-primary btn-sm">Editar</a>
          <a class="btn btn-danger btn-sm">Excluir</a>
      </td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>+55(16) 3325-6425</td>
      <td>18:50</td>
      <td>Cancelado</td>
      <td><a class="btn btn-primary btn-sm">Editar</a>
          <a class="btn btn-danger btn-sm">Excluir</a>
      </td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry the Bird</td>
      <td>+55(16) 5324-3845</td>
      <td>19:03</td>
      <td>Em andamento</td>
      <td><a class="btn btn-primary btn-sm">Editar</a>
          <a class="btn btn-danger btn-sm">Excluir</a>
      </td>
    </tr>
  </tbody>
</table>
</div>

Views/Order/OrderCad.cshtml
<div class="text-center">
<h1>@ViewData["Title"]</h1>
<div id="BackColor">
<form class="row g-3">
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Nome</label>
    <input type="text" class="form-control" placeholder="Insira Seu Nome">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Contato</label>
    <input type="text" class="form-control" placeholder="Insira seu Contato">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Endereço</label>
    <input type="text" class="form-control" placeholder="Insira Seu Endereço">
  </div>

    <div class="d-grid gap-2">
    <a asp-controller="Order" asp-action="" class="btn btn-primary ">Cadastrar Pedido</a>
    <a asp-controller="Order" asp-action="Index" class="btn btn-primary ">Voltar</a>
    </div>
    <br>
</form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza das bahianas assasinas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AMS23_Carousel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizza das bahianas assasinas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cadastrar
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Product">Produtos</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categoria</a></li>
                            </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Pedidos</a></li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;Pizza das bahianas assasinas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_carousel.cshtml
<div id="carouselProduct" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselProduct" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselProduct" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselProduct" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/pizzaDABOA.jpeg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/pizza.jpeg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/pizzaDiFlango.jpeg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselProduct" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselProduct" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>